# 条款08-别让异常逃离析构函数
---
+ C++不禁止在析构函数中吐出异常，但是它不喜欢你这样做。当容器或array并非遇上麻烦的必要条件，只要析构函数吐出异常，程序可能过早结束或出现不明确行为

+ 若一个程序一定要在析构函数执行一个动作，同时此动作可能会抛出异常。如一个用于数据库连接的class
```cpp
class DBConnection {
public:
	static DBConnection create();
	void close();
};
```

我们希望每次结束连接时，都会关闭连接，即调用`close()`，那么我们可以利用一个资源管理类(具体可见：第三部分-资源管理)，在析构函数中调用`close()`
```cpp
class DBConn{
public:
	...
	~DBConn();
private:
	DBConnection db;
}

DBConn::~DBConn() {
	db.close();
}
```

想法是十分美好的，如果一切正常运行。然而当`close()`调用出现异常时，会传播这个异常，即允许它离开这个析构函数，会导致一些难以解决的问题

有两个方法去解决这个问题

+ 若`close()`抛出异常，则结束程序。通常通过调用`abort()`实现
```cpp
DBConn::~DBConn() {
	try {
		db.close();
	} catch(...) {
		//制作日记log，记录下close()的调用失败
		std::abort();
	}
}
```

如果程序遇到一个于析构期间发生的错误无法继续执行，强迫结束程序是合理的。能够阻止异常从析构函数传播出去(会导致不明确行为)，也就是说调用`abort()`会抢先“制不明确行为”于死地

+ 吞下`close()`发生的异常
```cpp
DBConn::~DBConn() {
	try {
		db.close();
	} catch(...) {
		//制作日记log，记录下close()的调用失败
	}
}
```

一般来说，将异常吞掉是个坏主意，但是有时候吞下异常付出代价远不如“草率结束程序”

然而实际上，以上两个方法都并不十分好，因为两者都无法对“导致`close()`抛出异常”的情况做出反应。

+ 一个比较好的改进手法是，重新设计资源管理类`class DBConn`，让客户有一个能自己处理异常的机会
```cpp
class DBConn {
public:
	...
	void close();
	~DBConn();
private:
	DBConnecttion db;
	isClose = false;
}
void DBConn::close() {
		db.close();
		isClose = true;
}
DBConn::~DBConn() {
	if(!isClose) {
		try {
			db.close();
		} catch(...) {
			//制作日记log，记录下close()的调用失败
			...
		}
	}
}
```

+ 小结：
	+ 析构函数绝对不要吐出异常。若一个被析构函数调用的函数可能抛出异常，析构函数应该捕捉异常，然后吞下他们或结束程序
	+ 如果客户需要对某个操作函数运行期间抛出的异常做出反应，那么class应该提供一个函数让其执行操作